---
title: "Untitled"
author: "Joanna Yeung"
date: "2025-08-04"
output: html_document
---

# featureCounts, PCA & Correlation including HIRA Mutant counts under IvsM masterpeaks. 
```{r}
setwd("/lustre/fs4/risc_lab/scratch/jyeung/for_Hide/ATAC_deep_sequencing_Novogene_05072025/Justin_ATAC_pipeline/atac_7_featureCounts")
Mut_samplenames <- dir(pattern="atacHAK")[c(1,4,7,2,5,8,3,6,9)]
feature_MutCounts <- list()
for(i in 1:length(Mut_samplenames)){
  feature_MutCounts[[i]] <- read.table(paste0(Mut_samplenames[i],"/", Mut_samplenames[i], "_allOverlaps_IvsM_peakset_counts.txt"), skip=1, header=T) # read in feature_MutCounts file for each sample
  colnames(feature_MutCounts[[i]])[ncol(feature_MutCounts[[i]])] <- Mut_samplenames[i]
}
names(feature_MutCounts) <- Mut_samplenames

MutCounts <- matrix(nrow=nrow(feature_MutCounts[[1]]), ncol=length(feature_MutCounts), dimnames=list(feature_MutCounts[[1]]$Geneid, names(feature_MutCounts)))
for(i in 1:length(feature_MutCounts)){
  MutCounts[ ,i] <- as.integer(feature_MutCounts[[i]][, 7])
}

# make metaData from all samples
Mut_metaData <- data.frame(sample=Mut_samplenames, Condition=rep("Mitosis", length(Mut_samplenames)), Genotype=gsub(".*_", "", Mut_samplenames), Biorep=as.factor(rep(4:6, 3)))

# make DESeq object from frag_MutCounts matrix
dds <- DESeq2::DESeqDataSetFromMatrix(countData=MutCounts, design=~Biorep+Genotype, colData= Mut_metaData)
dds <- estimateSizeFactors(dds)
keep <- rowSums(counts(dds, normalize=T)) >= summary(rowSums(counts(dds, normalized=T)))[2]
dds <- dds[keep, ]
# perform DESeq
# all_IvsMpeaks.dds <- DESeq(all_IvsMpeaks.dds)
# rlog normalize for QC metrics visualization
rlogdds <- rlog(dds)


plotPCA(rlogdds, intgroup=c("Genotype"))+theme_classic()+ggtitle("Principal Component:top 500 most variable peaks")+scale_colour_manual(values=hm_cols$Genotype)

# get pearson correlation coefficients for pairwise comparisons between samples
sampleDists <- dist(t(assay(rlogall_IvsMpeaks.dds))) # get rlog normalized count matrix & convert to distance measure for calculating correlations. 
sampleDistMatrix <- as.matrix(sampleDists)
row.names(sampleDistMatrix) <- all_metaData$sample
# plot sample distance matrix
pdf_dir <- "/lustre/fs4/risc_lab/scratch/jyeung/for_Hide/ATAC_deep_sequencing_Novogene_10112024/Justin_ATAC_pipeline/post_peakcalling_analysis/Figures/"
pdf(paste0(pdf_dir, "sampleDistMatrix_IvsM.vsMutants.pdf"), width=5, height=4)
pheatmap(sampleDistMatrix,colorRampPalette(rev(c("white","white", "#FFFFB2","#FED976", "#FEB24C", "#FD8D3C", "#E31A1C", "#B10026")))(100), annotation_row = all_metaData[ ,-1], annotation_col = all_metaData[ ,-1], annotation_colors = hm_cols) # plot correlation heatmap
dev.off()
```


### plot PCA:
```{r}
# Generate PC names
pcs <- paste0("PC", 1:9)

# Get all unique pairwise combinations
pc_combinations <- combn(pcs, 2, simplify = FALSE)

# View first few combinations
head(pc_combinations)

# Optionally, format them for plotting (e.g., ggplot aesthetics)
pc_pairs <- lapply(pc_combinations, function(x) {
  list(x = x[1], y = x[2])
})
```

```{r}
# Assume your PCA results are in `pca_result_df`
# Columns PC1 to PC15 + metadata columns (Genotype, Batch, Biorep, etc.)

# Extract just the PCs
pca_results_df <- pca_result_df
pc_scores <- pca_result_df[ , grep("^PC", colnames(pca_result_df))]

# For each PC, run a linear model against Genotype
results <- lapply(colnames(pc_scores), function(pc) {
  model <- lm(pc_scores[[pc]] ~ pca_result_df$Genotype)
  summary_model <- summary(model)
  data.frame(
    PC = pc,
    R2 = summary_model$r.squared,
    p_value = anova(model)[["Pr(>F)"]][1]
  )
})

# Combine into a data frame
pc_genotype_assoc <- do.call(rbind, results)

# View which PCs are most associated with Genotype
pc_genotype_assoc[order(pc_genotype_assoc$p_value), ]
```

```{r}
# PCA based on all peaks
scaled_data <- scale(t(counts(all_IvsMpeaks.dds, normalized=T)[ ,-c(1:6)]))
# Compute variance of each peak across samples
peak_variances <- apply(scaled_data, 2, var)

# Get the names of the top 1000 most variable peaks
top_1000_peaks <- names(sort(peak_variances, decreasing = TRUE))[1:20000]

# Subset scaled_data to just these peaks
scaled_top_peaks <- scaled_data[, top_1000_peaks]

pca_result <- prcomp(scaled_top_peaks)
pca_result_df <- as.data.frame(pca_result$x)

pca_result_df <- cbind(pca_result_df, all_metaData[-c(1:6), ]) # include variables associated with samples

ggplot(data = pca_result_df) +
    geom_point(aes(x = "", y = PC1, color = Genotype, shape = Biorep), size = 3)
```

```{r}
# plot the variance explained by each PC
plot(1:length(pca_result$sdev), pca_result$sdev^2 / sum(pca_result$sdev^2),
     type = "b", xlab = "Principal Component", ylab = "Variance Explained")

# pca_result$x is where the sample is located in PCA space. 
pca_result_df <- as.data.frame(pca_result$x)

pca_result_df <- cbind(pca_result_df, all_metaData[-c(1:6), ]) # include variables associated with samples

VarianceExplained <- as.integer((pca_result$sdev^2 / sum(pca_result$sdev^2))*100) # variance explained by each PC 
# PC1 vs PC2

pca_result_df <- pca_result_df
pdf(paste0(pdf_dir, "PCA_HIRAmut.pdf"), width=10, height=8)
# Example loop over PC pairs
for (pair in pc_pairs) {
  pc_x <- pair$x
  pc_y <- pair$y

  x_var_exp <- VarianceExplained[pc_x]
  y_var_exp <- VarianceExplained[pc_y]

  p <- ggplot(data = pca_result_df) +
    geom_point(aes(x = .data[[pc_x]], y = .data[[pc_y]], color = Genotype, shape = Biorep), size = 3) +
    geom_text_repel(aes(x = .data[[pc_x]], y = .data[[pc_y]], label = sample)) +
    xlab(paste0(pc_x, ": ", round(x_var_exp, 1), "% Variance Explained")) +
    ylab(paste0(pc_y, ": ", round(y_var_exp, 1), "% Variance Explained")) +
    theme_classic() +
    ggtitle("PCA: Normalized counts, all Peaks") +
    scale_colour_manual(values = hm_cols$Genotype)

  print(p)
}
dev.off()
+
  scale_x_continuous(limits = c(-700,500))+
  scale_y_continuous(limits = c(-700,500))

# by treatment- top 500 most variable peaks
plotPCA(rlogdds, intgroup=c("Condition"))+theme_classic()+ggtitle("Principal Component:top 500 most variable peaks")+scale_colour_manual(values=hm_cols$Condition)+
  scale_x_continuous(limits = c(-30,30))+
  scale_y_continuous(limits = c(-30,30))

dev.off()

plotPCA(rlogall_IvsMpeaks.dds, intgroup=c("Genotype"))+theme_classic()+ggtitle("Principal Component:top 500 most variable peaks")+scale_colour_manual(values=hm_cols$Genotype)
```

```{r}
ggplot(data = pca_result_df) +
    geom_point(aes(x = "", y = PC1, color = Genotype, shape = Biorep), size = 3) +
  
    geom_text_repel(aes(x = .data[[pc_x]], y = .data[[pc_y]], label = sample)) +
    xlab(paste0(pc_x, ": ", round(x_var_exp, 1), "% Variance Explained")) +
    ylab(paste0(pc_y, ": ", round(y_var_exp, 1), "% Variance Explained")) +
    theme_classic() +
    ggtitle("PCA: Normalized counts, all Peaks") +
    scale_colour_manual(values = hm_cols$Genotype)
```
